name: Build 

on:
  push:
    branches: [ master, 'feature/*' ]
    tags: [ 'v*' ]

  pull_request:
    branches: [ master, 'feature/*' ]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install dependencies
      run: python -m pip install cpp-coveralls
    - name: Build, Run tests & coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: make coveralls

