name: Build 

on:
  push:
    branches: [ master, 'feature/*' ]
    tags: [ 'v*' ]

  pull_request:
    branches: [ master, 'feature/*' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build, Run tests
      run: |
        make clean
        make cover
  coveralls:
    runs-on: ubuntu-latest
    needs: tests
    # if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install dependencies
      run: python -m pip install cpp-coveralls
    - name: submit coverage result
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        make clean 
        make coveralls

